stages:
  - build
  - test
  - release

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

.default-before-script:
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

# Build
docker-build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:dind
  extends: .default-before-script
  script:
    - docker-compose build
    - docker tag quickshare_backend_web "$DOCKER_IMAGE_NAME"
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        docker tag quickshare_backend_web "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "dev"'

# Deploy
release:
  image: python:3.11
  stage: release
  before_script:
    - apt-get update && apt-get install -y python3-pip unzip curl git
    - pip install --upgrade pip
    - pip install awsebcli
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - apt-get update && apt-get install -y zip
  script:
    - |
      echo '{
        "AWSEBDockerrunVersion": "1",
        "Image": {
          "Name": "'$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG'",
          "Update": "true"
        },
        "Ports": [{"ContainerPort": 8000, "HostPort": 80}]
      }' > Dockerrun.aws.json
    - zip deploy.zip Dockerrun.aws.json
    # Ambiente dinamico in base al branch
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        export EB_ENV_NAME="QuickshareBack-env" 
      elif [[ "$CI_COMMIT_BRANCH" == "dev" ]]; then
        export EB_ENV_NAME="QuickshareBack-uat-env"
      fi
    - eb init QuickshareBack --platform docker --region "$AWS_DEFAULT_REGION"
    - eb use "$EB_ENV_NAME"
    - eb deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
