stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

docker-build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker-compose build
    - docker tag quickshare_backend_web "$DOCKER_IMAGE_NAME"
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag quickshare_backend_web "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


docker-test:
  image: docker:20.10.16
  stage: test
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - apk add --no-cache python3 py3-pip python3-dev build-base curl
    - ln -sf python3 /usr/bin/python  # Alias python → python3
    - python -V
    - python -m venv venv
    - . venv/bin/activate
    - pip install --upgrade pip
    - pip install pipenv
    - pipenv install
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker compose up -d
    - sleep 10
    - docker ps -a
     # Aspetta che il container sia healthy
    - |
      echo "Aspetto che il container sia healthy..."
      for i in {1..15}; do
        health=$(docker inspect --format='{{.State.Health.Status}}' quickshare_backend-web-1 2>/dev/null || echo "unknown")
        echo "Stato: $health"
        if [ "$health" = "healthy" ]; then
          break
        fi
        sleep 5
      done

      if [ "$health" != "healthy" ]; then
        echo "Container non è diventato healthy in tempo"
        docker ps -a
        docker logs quickshare_backend-web-1 || true
        curl --fail http://localhost:8000 || (echo "Container non risponde!" && exit 1)
        exit 1
      fi


    # Cleanup
    - docker compose down
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'