stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

docker-build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker-compose build
    - docker tag quickshare_web "$DOCKER_IMAGE_NAME"
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag quickshare_web "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

docker-test:
  image: docker:20.10.16
  stage: test
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker run -d --name test_app -p 8000:8000 "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - sleep 10
    - docker ps -a --filter name=test_app
    - curl --fail http://localhost:8000 || (echo "Container non risponde!" && exit 1)
    - docker stop test_app && docker rm test_app
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
