version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./Quickshare_backend:/app  # Solo se vuoi montare i file locali
      - ./staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=quickshare.settings  # Solo se lo usi

