version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:8000"
    env_file:
      - .env
    volumes:
      - ./Quickshare_backend:/app 
      - ./staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=quickshare.settings

