version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quickshare_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./Quickshare_backend:/app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn quickshare.wsgi:application --bind 0.0.0.0:8000"
